### ISSUE TITLE
modelPerformance() scores argument does not accept empty vecotr

### ISSUE THREAD

**Issue by maksymiuks** [MI2DataLab/auditor#106]
Hi

I wanted to create modelPerformance object with only measures passed via new.scores. Unfortuantely function rises an error when I pass NULL to scores

**Comment by agosiewska** [comment]
Thanks, I have fixed this.
Now, you can pass NULL

'''
titanic <- na.omit(DALEX::titanic)
titanic$survived <- titanic$survived == "yes"

# fit a model
model_glm <- glm(survived ~ ., family = binomial, data = titanic)
model_glm2 <- glm(survived ~ .-class, family = binomial, data = titanic)

# use DALEX package to wrap up a model into explainer
exp_glm <- DALEX::explain(model_glm, data = titanic, y = titanic$survived)
exp_glm2 <- DALEX::explain(model_glm2, data = titanic, y = titanic$survived, label = "glm2")

# validate a model with auditor
library(auditor)

ns1 <- function(exp){
  sqrt(sum(exp$residuals^2))
}

ns12 <- function(exp){
  sum(sqrt(abs(exp$residuals)))
}

ns10 <- function(exp){
  sum(abs(exp$residuals)^(1/10))
}


ns1(exp_glm)
ns12(exp_glm)
ns10(exp_glm)

mp <- auditor::model_performance(exp_glm, score = NULL, new_score = list(ns1 = ns1, ns12 = ns12, ns10 = ns10))
mp2 <- auditor::model_performance(exp_glm2, score = NULL, new_score = list(ns1 = ns1, ns12 = ns12, ns10 = ns10))

plot(mp, mp2)
'''
