### ISSUE TITLE
plotModelRanking does not work

### ISSUE THREAD

**Issue by maksymiuks** [MI2DataLab/auditor#108]
I've copied your example from https://mi2datalab.github.io/auditor/articles/model_performance_audit.html#model-ranking-radar-plot

```
lm_model <- lm(life_length ~ ., data = dragons)
lm_audit <- audit(lm_model, label = "lm", data = dragons, y = dragons$life_length)
lm_mp <- modelPerformance(lm_audit, scores = c("MAE", "MSE", "REC", "RROC"))
plot(lm_mp, table = TRUE)
```
and it created following warning

```
Warning messages:
1: In `[<-.factor`(`*tmp*`, ri, value = TRUE) :
  invalid factor level, NA generated
2: In `[<-.factor`(`*tmp*`, ri, value = TRUE) :
  invalid factor level, NA generated
3: In min(scoresDF$score) : no non-missing arguments to min; returning Inf
```

along with the plot on which every measure is presented with value 1

**Comment by agosiewska** [comment]
In #109 we've made many changes and now all examples and vignettes should work :)
I am closing this issue, but If you find examples that do not work, please, let me know :)
