### ISSUE TITLE
plotPrediction - some options to add

### ISSUE THREAD

**Issue by talgalili** [MI2DataLab/auditor#27]
1. To have the y axis show residuals instead of the actual values (y-y_predicted)
2. Add some smoothed line over the scatter plot (geom_smooth with method = 'loess' would do the job)

**Comment by agosiewska** [comment]
Thank you.

Ad 1. There is a function `plotResidual()` which shows residuals on the y-axis. 
I am currently preparing a table containing a brief and user-friendly overview of auditor functionalities, I hope it'll make it easier to find needed functions.

Ad 2. Added

**Comment by talgalili** [comment]
(Y)
