### ISSUE TITLE
Cleanup in arguments of plotting functions

### ISSUE THREAD

**Issue by tmikolajczyk** [MI2DataLab/auditor#58]

**Comment by tmikolajczyk** [comment]
- [ ] remove `alpha` from `plotACF` & `plotPrediction`
- [ ] `plotModelRanking` - change `scores` to `score`
- [ ] `plotResidualDensity` - change `split.var` to `split`
- [ ] `plotHalfNormal` - remove `xlab` and `ylab`

**Comment by hbaniecki** [comment]
https://docs.google.com/spreadsheets/d/1PRe29KKB3ZqOMVvEIxZHvY8TDTxj0Tpeq32e4NMLzfs/edit#gid=686573002

**Comment by agosiewska** [comment]
plotModelRanking - change scores to score
 done in #109 
We can close this issue now :)
