### ISSUE TITLE
plotLIFT doesn't support response variables coded as TRUE/FALSE

### ISSUE THREAD

**Issue by sztach** [MI2DataLab/auditor#96]
When I tried to use plotLIFT function with boolean response, it threw the following error:

Error in ROCR::prediction(predictions, y) : 
  Number of classes is not equal to 2.
ROCR currently supports only evaluation of binary classification tasks.
In addition: Warning message:
In getCGainsDF(object) : NAs introduced by coercion

As I digged into the code the problem is with the last function (getCGainsDf) in the following line
`y <- as.numeric(as.character(object$y))`

If object$y is a vector of boolean values, they are changed into NAs. 

Reproducible example:
```
library('auditor')


# this works fine
data('iris')
iris$Species <- ifelse(iris$Species == 'setosa', 1, 0)
model1 <- glm(Species ~., data = iris)
audit1 <- audit(model1, iris[, -5], iris$Species)
plotLIFT(audit1)


# this code throws an error
data('iris')
iris$Species <- iris$Species == 'setosa'
model2 <- glm(Species ~., data = iris)
audit2 <- audit(model2, iris[, -5], iris$Species)
plotLIFT(audit2)
```

**Comment by agosiewska** [comment]
Hey, It works now in new version of auditor )

```
titanic <- na.omit(DALEX::titanic)
titanic$survived <- titanic$survived == "yes"

# fit a model
model_glm <- glm(survived ~ ., family = binomial, data = titanic)

# use DALEX package to wrap up a model into explainer
exp_glm <- DALEX::explain(model_glm, data = titanic, y = titanic$survived)

# validate a model with auditor
library(auditor)
eva_glm <- model_evaluation(exp_glm)
plot_roc(eva_glm)
```
